name: alshatbe_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  easy_localization: ^3.0.0
  hive_flutter: ^1.1.0
  hive: ^2.2.3
  url_launcher: ^6.1.7
  image_picker: ^1.0.0
  font_awesome_flutter: ^10.1.0
  syncfusion_flutter_charts: ^20.4.0
  geolocator: ^9.0.2
  geocoding: ^2.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/translations/
    - assets/images/logo.png
  fonts:
    - family: Cairo
      fonts:
        - asset: assets/fonts/Cairo-Regular.ttf
        - asset: assets/fonts/Cairo-Bold.ttf
          weight: 700
